<?php

use yii\db\Migration;

class m170523_064346_add_table_info extends Migration
{
    public function up()
    {
        $this->execute("CREATE TABLE `info` (
          `id` int(11) NOT NULL AUTO_INCREMENT,
          `view` varchar(64) NOT NULL,
          `title` varchar(256) DEFAULT NULL,
          `description` mediumtext NOT NULL,
          PRIMARY KEY (`id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8;");

        $this->execute("INSERT INTO `info` (`id`, `view`, `title`, `description`) VALUES
            (1,	'info-offer-type',	'',	'<p>Bei Jugl gibt es drei verschiedene Arten von Werbung. Angebote ohne Kaufoption dienen der Information. Bei Angeboten mit der Sofortkauf-Option kannst Du nach dem Lesen der Werbung direkt auf den &bdquo;kaufen&ldquo;-Button klicken und dir das Angebot sichern. Die dritte Option ist das Bieterverfahren. Hier siehst Du in der Werbung die Preisvorstellung des Verk&auml;ufers und kannst anschlie&szlig;end mit einem Klick auf den &bdquo;verbindlich bieten&ldquo;-Button dein Gebot abgeben. Dieses muss nicht unbedingt der Preisvorstellung des Verk&auml;ufers entsprechen, es kann auch h&ouml;her oder niedriger sein. Denn entscheidend ist nicht die H&ouml;he des Gebots, der Verk&auml;ufer kann einen beliebigen K&auml;ufer ausw&auml;hlen.</p>\r\n'),
            (2,	'view-activities',	'Meine Aktivitäten',	'<p>Bleibe auf dem neuesten Stand: Dein Aktivit&auml;tenordner zeigt dir an, was in deinem Jugl-Account passiert, z.B. Kontoein- und -ausg&auml;nge, neue Kontakte oder Einladungsannahmen. Mit einem Klick auf die Aktivit&auml;t kommst Du direkt in den entsprechenden Bereich.</p>\r\n'),
            (3,	'view-contact',	'',	'<p>- einmal lange im Chat auf das Feld klicken = Gespr&auml;chsverlauf l&ouml;schen</p>\r\n\r\n<p>- Bilder, Video oder Dateien versenden = klicken auf + Button</p>\r\n\r\n<p>- markieren, l&ouml;schen oder weiterleiten = einmal lange auf die entsprechende Nachricht klicken</p>\r\n'),
            (4,	'view-deals-completed',	'Abgeschlossene Geschäfte & Bewertungen',	'<p>Mit einem Klick kannst Du dir jeden Abgeschlossene Handel, jede Recherche oder Vermittlung noch einmal ansehen und eine Bewertung abgeben oder bereits abgegebene Bewertungen &auml;ndern. 1 Stern ist schlecht, 5 Sterne sind super.</p>\r\n'),
            (5,	'view-earn-money',	'So funktioniert Jugl',	'<p><strong>Lade Deine Freunde zu Jugl ein.</strong></p>\r\n\r\n<p>F&uuml;r jeden Freund, der sich durch Deine Einladung registriert, bekommst Du 100 Jugls (1&euro;). Wenn Deine Freunde wiederum Freunde einladen, erh&auml;ltst Du jeweils 29% von deren Gewinn und wenn diese wiederum Freunde einladen das Gleiche usw. usw. usw.. So kannst Du dir ein lukratives Netzwerk aufbauen, an dem Du ganz nebenbei mitverdienst.</p>\r\n\r\n<p>Also klicke im Men&uuml; einfach auf &quot;Freunde einladen&quot; und schon rollt der Jugl.</p>\r\n'),
            (6,	'view-favorites',	'Mein Merkzettel',	'<p>Hier siehst Du alles, was Du Dir f&uuml;r sp&auml;ter gemerkt hast. Dazu geh&ouml;ren sowohl Werbungen, also auch Suchauftr&auml;ge anderer Mitglieder.</p>\r\n'),
            (7,	'view-forum',	'Jugl Forum',	'<p>Nutze das Jugl Forum um mit anderen Mitgliedern in Kontakt zu bleiben. Hier kann sich unsere Gemeinschaft austauschen.</p>\r\n\r\n<p>Um einen Post zu bewerten, klicke auf Daumen hoch bzw. Daumen runter.</p>\r\n\r\n<p>Um auf einen Post zu antworten, klicke einfach auf den Kommentieren-Button.<br />\r\nDu gelangst dann in einen Chat mit allen Mitgliedern, die auf diesen Post reagiert haben.</p>\r\n\r\n<p>Hier zu werben ist nicht gestattet und auch unfair gegen&uuml;ber denen, die den Usern hier auch Jugls zahlen daf&uuml;r, dass sie sich ihre Werbung ansehen. Wenn Du werben m&ouml;chtest, kannst Du das gerne &uuml;ber die &quot;Anzeigen&quot;-Funktion machen.</p>\r\n\r\n<p>Helft bitte alle mit, dass unser Forum nicht zu Werbezwecken missbraucht wird.</p>\r\n\r\n<p>Wenn Du als Ersteller eines Posts diesen l&ouml;schen m&ouml;chtest, dann klicke in der Messenger&uuml;bersicht lange auf den Chat und l&ouml;sche ihn dort. Er ist dann f&uuml;r alle Mitglieder nicht mehr sichtbar.</p>\r\n'),
            (8,	'view-funds-app',	'Mein Jugl-Konto',	'<p>Behalte Deinen Kontostand und Deine Transaktionen im Blick.</p>\r\n\r\n<p>Mehr Infos &uuml;ber die Transaktion erh&auml;ltst Du, wenn Du auf <span class=\\\"funds - collapsible - plus - icon\\\"></span> klickst</p>\r\n'),
            (9,	'view-funds-web',	'Mein Jugl-Konto',	'<p>Behalte deinen Kontostand und deine Transaktionen im Blick.</p>\r\n'),
            (10,	'view-interests-offer',	'Meine Interessen',	'<p>Gib deine Interessen an. Auf diesen Angaben basiert die Werbung, die dir angezeigt wird. Je genauer Du deine Interessen kennzeichnest, desto pr&auml;ziser entsprechen die angebotenen Produkte deinen Bed&uuml;rfnissen. F&uuml;r jede gelesene Werbeanzeige verdienst Du Jugl, die deinem Konto zugeschrieben werden. Es lohnt sich also f&uuml;r dich, viele Interessen anzugeben.</p>\r\n'),
            (11,	'view-interests-search-request',	'Meine Interessen',	'<p>Wenn Du lange auf eine Kategorie klickst, werden Dir eventuelle Unterkategorien angezeigt.</p>\r\n'),
            (12,	'view-invite',	'Freunde einladen und gemeinsam Geld verdienen',	'<p>Freunde einladen ist die sch&ouml;nste und wichtigste Funktion bei jugl.net. Hier baust Du Dir Dein Netzwerk und Dein passives Einkommen auf. Lebenslang profitierst Du von den wenigen Minuten, die Du hier investierst und Deine Freunde werden es Dir danken. Ihr verdient zusammen Geld und baut euch was f&uuml;r die Zukunft auf. Klicke einfach auf ,,Freunde einladen&rsquo;&rsquo; und w&auml;hle eine der Methoden aus. Wenn du eine SMS-Flatrate hast, empfehlen wir Dir, per SMS einzuladen. Setze bei allen Kontakten, die Du einladen m&ouml;chtest, einfach einen Haken und klicke auf einladen.</p>\r\n'),
            (13,	'view-invite-log',	'Einladungshistorie',	'<p>Eingeladene Kontakte sind dein Kapital bei Jugl. Denn Du wirst an allen ihren Einnahmen beteiligt. Hier kannst Du sehen, wer deine Einladung angenommen bzw. nicht angenommen hat. Du kannst deinen Bekannten zu einem sp&auml;teren Zeitpunkt erneut eine Einladung senden.</p>\r\n'),
            (14,	'view-invite-my-list',	'Netzwerk aufbauen',	'<p>Hier bitten User darum, ins Netzwerk eingeladen zu werden. Wenn Du sie einl&auml;dst, kommen sie in Dein Netzwerk und erhalten eine Nachricht von Dir. Du bist dann f&uuml;r Deine neuen Mitglieder zust&auml;ndig und hilfst ihnen, wenn Fragen oder Probleme auftreten sollten.</p>\r\n\r\n<p>F&uuml;r Mitglieder, die Du &uuml;ber diese Funktion einl&auml;dst, erh&auml;ltst Du keinen Werbebonus.</p>\r\n'),
            (15,	'view-network',	'Mein Jugl-Netzwerk',	'<p>Je gr&ouml;&szlig;er das Netzwerk deiner Freunde und Freundesfreunde, desto gr&ouml;&szlig;er sind deine Verdienstm&ouml;glichkeiten. Denn Du verdienst an den Einnahmen derer, die Du eingeladen hast und an den Einnahmen derer, die wiederum deine eingeladenen Kontakte eingeladen haben usw. Hier siehst Du alle Mitglieder, die direkt durch Dich oder durch Mitglieder in Deinem Netzwerk eingeladen worden sind.</p>\r\n'),
            (16,	'view-news',	'News',	'<p>Hier findest Du immer die neuesten und aktuellsten Veranstaltungen, Neuigkeiten und Videos von jugl.net.</p>\r\n'),
            (17,	'view-offers-add',	'Verkaufen / Werbung schalten',	'<p>Hier kannst Du deine Werbung erstellen. Dabei gibt es die M&ouml;glichkeit, eine Werbung mit Kaufoption oder ohne Kaufoption zu schalten. Du kannst deine potentiellen K&auml;ufer aber auch Gebote f&uuml;r dein Angebot abgeben lassen und Dich entscheiden, wem Du den Zuschlag gibst. Einen Werbebonus erh&auml;lt jeder, der sich Deine Werbung ansieht. Der Kaufbonus wird dem K&auml;ufer ausgezahlt, wenn er sich f&uuml;r Dein Angebot entscheidet (nur bei Sofortkauf und bieten).</p>\r\n'),
            (18,	'view-offers-my',	'Meine Anzeigen / Werbung verwalten',	'<p>Alles im Blick: Hier bekommst Du jederzeit eine &Uuml;bersicht mit deinen geschalteten Werbeaktionen. Du kannst die Aktionen bearbeiten oder l&ouml;schen und dein Werbebudget anpassen. Zudem zeigen wir dir Kaufinteressenten, die sich &uuml;ber deine Produkte informieren m&ouml;chten.</p>\r\n'),
            (19,	'view-offers-my-requests',	'Ich habe geboten / gekauft',	'<p>Diese Ansicht bietet Dir eine &Uuml;bersicht &uuml;ber all Deine erfolgreichen K&auml;ufe.</p>\r\n\r\n<p>Zudem findest Du hier die Gebote, die Du auf Anzeigen im Bieterverfahren abgegeben hast und kannst sowohl deren H&ouml;he als auch G&uuml;ltigkeit ver&auml;ndern.</p>\r\n'),
            (20,	'view-offers-search',	'Kaufen / Suchergebnisse / Werbung lesen',	'<p>Verdiene Jugls mit Anzeigen lesen und dem allt&auml;glichen Einkauf: Basierend auf deinen Interessen haben wir f&uuml;r dich deinen individuellen Produktkatalog zusammengestellt. Die Anzeigen sind nach dem Grad der &Uuml;bereinstimmung mit deinen Interessen sortiert. Du kannst sie aber auch nach anderen Kriterien filtern. Bereits f&uuml;r das Ansehen der Anzeigen wird dir ein Werbebonus gutgeschrieben. Wenn Du ein Produkt kaufen m&ouml;chtest, klicke einfach auf &bdquo;Angebot annehmen&ldquo;. Der Anbieter wird sich dann bei dir melden, um den Kauf abzuschlie&szlig;en. Ist der Kauf abgeschlossen, bekommst Du automatisch deinen Kaufbonus auf deinem Jugl-Konto angerechnet.</p>\r\n'),
            (21,	'view-profile',	'Mein Profil / Meine Daten',	'<p>Gestalte dein Profil. Je genauer dein Profil ist, desto eher entsprechen die Anzeigen deinen Interessen und Bed&uuml;rfnissen und um so h&ouml;her sind deine Einnahmechancen. &Uuml;ber die Sichtbarkeitseinstellungen hast Du jederzeit die volle Kontrolle &uuml;ber deine Daten und dar&uuml;ber, wem Du etwas preisgibst. Im Gegensatz zu anderen Plattformen sehen H&auml;ndler und private Produktanbieter, die Anzeigen schalten, grunds&auml;tzlich keine pers&ouml;nlichen Profildaten. Sie spielen ihre Anzeigen an anonymisierten Interessentengruppen aus (zum Beispiel an alle M&auml;nner zwischen 20 und 30).</p>\r\n'),
            (22,	'view-searches-add',	'Auftrag erstellen',	'<p>Hier kannst Du andere Mitglieder beauftragen oder sie recherchieren bzw. suchen lassen.</p>\r\n\r\n<p>Zum Beispiel muss Deine Wohnung renoviert werden:</p>\r\n\r\n<p>&quot;Ich suche jemanden, der meine Wohnung zum Preis X renoviert. Oder kennst Du jemanden, der meine Wohnung renovieren kann, dann zahle ich Dir f&uuml;r die Vermittlung einen Vermittlungsbonus von XX Jugls.&quot;</p>\r\n\r\n<p>Du erh&auml;ltst dadurch 1. direkte Angebote zur Wohnungsrenovierung und 2. gute Tipps und Vorschl&auml;ge.</p>\r\n\r\n<p>Der Vermittlungsbonus ist gleichzeitig eine Geb&uuml;hr f&uuml;r einen angenommenen Auftrag bzw. eine angenommene Suche/Recherche. Von dieser Geb&uuml;hr geht auch ein Teil in das Netzwerk und unterst&uuml;tzt die Jugl-Community.</p>\r\n\r\n<p>Der Vermittlungsbonus muss angemessen sein (ca. 1-5% vom Preis).</p>\r\n\r\n<p>Den Vermittlungsbonus musst Du nur bezahlen, wenn Du ein Angebot annimmst.</p>\r\n'),
            (23,	'view-searches-index',	'Suchauftrag erstellen / recherchieren / vermitteln',	'<p>Du suchst etwas und hast keine Zeit oder Lust, selbst im Internet zu recherchieren? Dann gib eine Recherche in Auftrag. Die Jugl-Suche ist eine menschliche Suchmaschine. Ihr Vorteil: Du sparst Zeit, Geld und bekommst bessere Ergebnisse. Denn keine der herk&ouml;mmlichen Suchmaschinen wird dir jemals den besten Flug oder das beste Gebrauchtwagenangebot raussuchen k&ouml;nnen. Die Suchmaschinen-Algorithmen wissen nicht, worauf es dir ankommt. In der Jugl-Suche kannst Du dagegen andere Mitglieder aus dem Netzwerk f&uuml;r einen kleinen Bonus beauftragen, f&uuml;r dich zu suchen oder einen Anbieter f&uuml;r dein Anliegen direkt zu vermitteln. Beschreibe m&ouml;glichst genau, nach was Du suchst. Andere Jugl-Mitglieder werden dir ein entsprechendes Angebot f&uuml;r die Recherche zuschicken.</p>\r\n'),
            (24,	'view-searches-my',	'Auftrag annehmen',	'<p>Hier siehst Du auf einen Blick alle Angebote auf Deine Auftr&auml;ge. Du kannst passende Angebote annehmen und dem Anbieter eine Nachricht schreiben, um Details zu kl&auml;ren. Zudem kannst Du die Angebote bewerten und den Status abfragen.</p>\r\n\r\n<p>Wichtig: Durch die Annahme passender Angebote erwirbst Du nicht das darin enthaltene Produkt, sondern bezahlst dem Anbieter einen Bonus f&uuml;r seine Recherche.</p>\r\n\r\n<p>Anbieter und Auftraggeber stimmen sich bez&uuml;glich der Bezahlung des Auftrags selbst ab.</p>\r\n'),
            (25,	'view-searches-my-offers',	'Was habe ich anderen vermittelt',	'<p>Hier siehst Du Alle Suchauftr&auml;ge, auf die Du ein Angebot abgegeben hast. Dir wird angezeigt, ob der Suchende diese bereits angenommen bzw. abgelehnt hat oder ob eine Entscheidung noch ausstehend ist.</p>\r\n'),
            (26,	'view-searches-offer-add',	'Angebot abgeben',	'<p>Hier kannst Du dem Auftraggeber etwas anbieten oder vermitteln.</p>\r\n\r\n<p>In das erste Feld kannst Du einen Text eintragen, in das zweite Feld ein Bild.</p>\r\n\r\n<p>Diese Informationen werden dem Auftraggeber angezeigt.</p>\r\n\r\n<p>In das dritte und vierte Feld kannst Du etwas eintragen, was dem Auftraggeber erst angezeigt wird, wenn er Dein Angebot angenommen hat.</p>\r\n\r\n<p>Beispiel, Du hast f&uuml;r jemanden eine interessante Website gefunden oder die passende Wohnung &ndash; dann kannst Du im ersten Teil des Angebots (sichtbar) die Website oder die Wohnung beschreiben und im zweiten Teil kannst Du den Link zur Website angeben oder die Telefonnummer des Vermieters, sodass diese Informationen erst angezeigt werden, wenn Du Deinen Vermittlungsbonus erhalten hast.</p>\r\n\r\n<p>Nat&uuml;rlich kannst Du, wenn Du selbst Vermieter bist, Deine Wohnung anbieten.</p>\r\n\r\n<p>Du erh&auml;ltst den Vermittlungsbonus in dem Moment, in dem der Auftraggeber Deine Angebot annimmt.</p>\r\n'),
            (27,	'view-searches-search',	'Auftrag',	'<p>Jeder Mensch, ob mit oder ohne Gewerbe, braucht immer wieder in seinem Leben Hilfe.</p>\r\n\r\n<p>Egal ob gro&szlig;e oder kleine Hilfe, bei Jugl.net gibt es tausende von Helfern, die genau f&uuml;r Dich das Richtige finden oder Deinen Auftrag &uuml;bernehmen.</p>\r\n\r\n<p>Dazu kannst Du sie beauftragen oder auch selbst einen Auftrag annehmen. Oder recherchieren oder suchen, oder suchen lassen.</p>\r\n\r\n<p>F&uuml;r diese Suche oder Recherche zahlst Du einen Vermittlungsbonus.</p>\r\n\r\n<p>Der Vermittlungsbonus ist gleichzeitig eine Geb&uuml;hr f&uuml;r einen angenommenen Auftrag bzw. eine angenommene Suche/Recherche. Von dieser Geb&uuml;hr geht auch ein Teil in das Netzwerk und unterst&uuml;tzt die Jugl-Community.</p>\r\n\r\n<p>Der Vermittlungsbonus muss angemessen sein (ca. 1-5% vom Preis).</p>\r\n'),
            (28,	'view-settings',	'Einstellungen',	'<p>Konfiguriere deinen Jugl-Account nach deinen Bed&uuml;rfnissen. Du kannst Pop-ups ein- und ausschalten, dir Erkl&auml;rtexte anzeigen lassen, Ton einstellen und vieles mehr.</p>\r\n'),
            (29,	'view-user-search',	'Mitglieder suchen',	'<p>Finde Jugl-Mitglieder und nimm Kontakt ihnen auf.</p>\r\n');");
    }

    public function down()
    {
        echo "m170523_064346_add_table_info cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
