<?php

namespace app\models;

use Yii;

class Country extends \app\models\base\Country
{
    /**
    * @inheritdoc
    */

//    public static function getList() {
//        $items=[];
//        foreach(static::find()->orderBy('sort_order')->all() as $model) {
//            $items[$model->id]=$model->country;
//        }
//        return $items;
//    }

    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app','ID'),
            'country' => Yii::t('app','Country'),
            'sort_order' => Yii::t('app','Sort Order'),
        ];
    }


    public static function getList($id=null) {

        $countries = [
            64=>Yii::t('app', 'Germany'),
            10=>Yii::t('app', 'Austria'),
            170=>Yii::t('app', 'Switzerland'),
            1=>Yii::t('app', 'Afghanistan'),
            2=>Yii::t('app', 'Albania'),
            3=>Yii::t('app', 'Algeria'),
            4=>Yii::t('app', 'Andorra'),
            5=>Yii::t('app', 'Angola'),
            6=>Yii::t('app', 'Antigua & Deps'),
            7=>Yii::t('app', 'Argentina'),
            8=>Yii::t('app', 'Armenia'),
            9=>Yii::t('app', 'Australia'),
            11=>Yii::t('app', 'Azerbaijan'),
            12=>Yii::t('app', 'Bahamas'),
            13=>Yii::t('app', 'Bahrain'),
            14=>Yii::t('app', 'Bangladesh'),
            15=>Yii::t('app', 'Barbados'),
            16=>Yii::t('app', 'Belarus'),
            17=>Yii::t('app', 'Belgium'),
            18=>Yii::t('app', 'Belize'),
            19=>Yii::t('app', 'Benin'),
            20=>Yii::t('app', 'Bhutan'),
            21=>Yii::t('app', 'Bolivia'),
            22=>Yii::t('app', 'Bosnia Herzegovina'),
            23=>Yii::t('app', 'Botswana'),
            24=>Yii::t('app', 'Brazil'),
            25=>Yii::t('app', 'Brunei'),
            26=>Yii::t('app', 'Bulgaria'),
            27=>Yii::t('app', 'Burkina'),
            28=>Yii::t('app', 'Burundi'),
            29=>Yii::t('app', 'Cambodia'),
            30=>Yii::t('app', 'Cameroon'),
            31=>Yii::t('app', 'Canada'),
            32=>Yii::t('app', 'Cape Verde'),
            33=>Yii::t('app', 'Central African Rep'),
            34=>Yii::t('app', 'Chad'),
            35=>Yii::t('app', 'Chile'),
            36=>Yii::t('app', 'China'),
            37=>Yii::t('app', 'Colombia'),
            38=>Yii::t('app', 'Comoros'),
            39=>Yii::t('app', 'Congo'),
            40=>Yii::t('app', 'Congo (Democratic Rep)'),
            41=>Yii::t('app', 'Costa Rica'),
            42=>Yii::t('app', 'Croatia'),
            43=>Yii::t('app', 'Cuba'),
            44=>Yii::t('app', 'Cyprus'),
            45=>Yii::t('app', 'Czech Republic'),
            46=>Yii::t('app', 'Denmark'),
            47=>Yii::t('app', 'Djibouti'),
            48=>Yii::t('app', 'Dominica'),
            49=>Yii::t('app', 'Dominican Republic'),
            50=>Yii::t('app', 'East Timor'),
            51=>Yii::t('app', 'Ecuador'),
            52=>Yii::t('app', 'Egypt'),
            53=>Yii::t('app', 'El Salvador'),
            54=>Yii::t('app', 'Equatorial Guinea'),
            55=>Yii::t('app', 'Eritrea'),
            56=>Yii::t('app', 'Estonia'),
            57=>Yii::t('app', 'Ethiopia'),
            58=>Yii::t('app', 'Fiji'),
            59=>Yii::t('app', 'Finland'),
            60=>Yii::t('app', 'France'),
            61=>Yii::t('app', 'Gabon'),
            62=>Yii::t('app', 'Gambia'),
            63=>Yii::t('app', 'Georgia'),
            65=>Yii::t('app', 'Ghana'),
            66=>Yii::t('app', 'Greece'),
            67=>Yii::t('app', 'Grenada'),
            68=>Yii::t('app', 'Guatemala'),
            69=>Yii::t('app', 'Guinea'),
            70=>Yii::t('app', 'Guinea-Bissau'),
            71=>Yii::t('app', 'Guyana'),
            72=>Yii::t('app', 'Haiti'),
            73=>Yii::t('app', 'Honduras'),
            74=>Yii::t('app', 'Hungary'),
            75=>Yii::t('app', 'Iceland'),
            76=>Yii::t('app', 'India'),
            77=>Yii::t('app', 'Indonesia'),
            78=>Yii::t('app', 'Iran'),
            79=>Yii::t('app', 'Iraq'),
            80=>Yii::t('app', 'Ireland'),
            81=>Yii::t('app', 'Israel'),
            82=>Yii::t('app', 'Italy'),
            83=>Yii::t('app', 'Ivory Coast'),
            84=>Yii::t('app', 'Jamaica'),
            85=>Yii::t('app', 'Japan'),
            86=>Yii::t('app', 'Jordan'),
            87=>Yii::t('app', 'Kazakhstan'),
            88=>Yii::t('app', 'Kenya'),
            89=>Yii::t('app', 'Kiribati'),
            90=>Yii::t('app', 'Korea North'),
            91=>Yii::t('app', 'Korea South'),
            92=>Yii::t('app', 'Kosovo'),
            93=>Yii::t('app', 'Kuwait'),
            94=>Yii::t('app', 'Kyrgyzstan'),
            95=>Yii::t('app', 'Laos'),
            96=>Yii::t('app', 'Latvia'),
            97=>Yii::t('app', 'Lebanon'),
            98=>Yii::t('app', 'Lesotho'),
            99=>Yii::t('app', 'Liberia'),
            100=>Yii::t('app', 'Libya'),
            101=>Yii::t('app', 'Liechtenstein'),
            102=>Yii::t('app', 'Lithuania'),
            103=>Yii::t('app', 'Luxembourg'),
            104=>Yii::t('app', 'Macedonia'),
            105=>Yii::t('app', 'Madagascar'),
            106=>Yii::t('app', 'Malawi'),
            107=>Yii::t('app', 'Malaysia'),
            108=>Yii::t('app', 'Maldives'),
            109=>Yii::t('app', 'Mali'),
            110=>Yii::t('app', 'Malta'),
            111=>Yii::t('app', 'Marshall Islands'),
            112=>Yii::t('app', 'Mauritania'),
            113=>Yii::t('app', 'Mauritius'),
            114=>Yii::t('app', 'Mexico'),
            115=>Yii::t('app', 'Micronesia'),
            116=>Yii::t('app', 'Moldova'),
            117=>Yii::t('app', 'Monaco'),
            118=>Yii::t('app', 'Mongolia'),
            119=>Yii::t('app', 'Montenegro'),
            120=>Yii::t('app', 'Morocco'),
            121=>Yii::t('app', 'Mozambique'),
            122=>Yii::t('app', 'Myanmar, (Burma)'),
            123=>Yii::t('app', 'Namibia'),
            124=>Yii::t('app', 'Nauru'),
            125=>Yii::t('app', 'Nepal'),
            126=>Yii::t('app', 'Netherlands'),
            127=>Yii::t('app', 'New Zealand'),
            128=>Yii::t('app', 'Nicaragua'),
            129=>Yii::t('app', 'Niger'),
            130=>Yii::t('app', 'Nigeria'),
            131=>Yii::t('app', 'Norway'),
            132=>Yii::t('app', 'Oman'),
            133=>Yii::t('app', 'Pakistan'),
            134=>Yii::t('app', 'Palau'),
            135=>Yii::t('app', 'Panama'),
            136=>Yii::t('app', 'Papua New Guinea'),
            137=>Yii::t('app', 'Paraguay'),
            138=>Yii::t('app', 'Peru'),
            139=>Yii::t('app', 'Philippines'),
            140=>Yii::t('app', 'Poland'),
            141=>Yii::t('app', 'Portugal'),
            142=>Yii::t('app', 'Qatar'),
            143=>Yii::t('app', 'Romania'),
            144=>Yii::t('app', 'Russian Federation'),
            145=>Yii::t('app', 'Rwanda'),
            146=>Yii::t('app', 'St Kitts & Nevis'),
            147=>Yii::t('app', 'St Lucia'),
            148=>Yii::t('app', 'Saint Vincent & the Grenadines'),
            149=>Yii::t('app', 'Samoa'),
            150=>Yii::t('app', 'San Marino'),
            151=>Yii::t('app', 'Sao Tome & Principe'),
            152=>Yii::t('app', 'Saudi Arabia'),
            153=>Yii::t('app', 'Senegal'),
            154=>Yii::t('app', 'Serbia'),
            155=>Yii::t('app', 'Seychelles'),
            156=>Yii::t('app', 'Sierra Leone'),
            157=>Yii::t('app', 'Singapore'),
            158=>Yii::t('app', 'Slovakia'),
            159=>Yii::t('app', 'Slovenia'),
            160=>Yii::t('app', 'Solomon Islands'),
            161=>Yii::t('app', 'Somalia'),
            162=>Yii::t('app', 'South Africa'),
            163=>Yii::t('app', 'South Sudan'),
            164=>Yii::t('app', 'Spain'),
            165=>Yii::t('app', 'Sri Lanka'),
            166=>Yii::t('app', 'Sudan'),
            167=>Yii::t('app', 'Suriname'),
            168=>Yii::t('app', 'Swaziland'),
            169=>Yii::t('app', 'Sweden'),
            171=>Yii::t('app', 'Syria'),
            172=>Yii::t('app', 'Taiwan'),
            173=>Yii::t('app', 'Tajikistan'),
            174=>Yii::t('app', 'Tanzania'),
            175=>Yii::t('app', 'Thailand'),
            176=>Yii::t('app', 'Togo'),
            177=>Yii::t('app', 'Tonga'),
            178=>Yii::t('app', 'Trinidad & Tobago'),
            179=>Yii::t('app', 'Tunisia'),
            180=>Yii::t('app', 'Turkey'),
            181=>Yii::t('app', 'Turkmenistan'),
            182=>Yii::t('app', 'Tuvalu'),
            183=>Yii::t('app', 'Uganda'),
            184=>Yii::t('app', 'Ukraine'),
            185=>Yii::t('app', 'United Arab Emirates'),
            186=>Yii::t('app', 'United Kingdom'),
            187=>Yii::t('app', 'United States'),
            188=>Yii::t('app', 'Uruguay'),
            189=>Yii::t('app', 'Uzbekistan'),
            190=>Yii::t('app', 'Vanuatu'),
            191=>Yii::t('app', 'Vatican City'),
            192=>Yii::t('app', 'Venezuela'),
            193=>Yii::t('app', 'Vietnam'),
            194=>Yii::t('app', 'Yemen'),
            195=>Yii::t('app', 'Zambia'),
            196=>Yii::t('app', 'Zimbabwe')
        ];
		if($id==null){
		 return $countries;	
		}
		else{
		 return $countries[$id];	
		}
       
    }
	
	public static function getListShort($id=null) {

        $countries = [
            64=>'de',
            10=>'at',
            170=>'ch',
            1=>'af',
            2=>'al',
            3=>'dz',
            4=>'ad',
            5=>'ao',
            6=>'ag',
            7=>'ar',
            8=>'am',
            9=>'au',
            11=>'az',
            12=>'bs',
            13=>'bh',
            14=>'bd',
            15=>'bb',
            16=>'by',
            17=>'be',
            18=>'bz',
            19=>'bj',
            20=>'bt',
            21=>'bo',
            22=>'ba',
            23=>'bw',
            24=>'br',
            25=>'bn',
            26=>'bg',
            27=>'bf',
            28=>'bi',
            29=>'kh',
            30=>'cm',
            31=>'ca',
            32=>'cv',
            33=>'cf',
            34=>'td',
            35=>'cl',
            36=>'cn',
            37=>'co',
            38=>'km',
            39=>'cg',
            40=>'cd',
            41=>'cr',
            42=>'hr',
            43=>'cu',
            44=>'cy',
            45=>'cz',
            46=>'dk',
            47=>'dj',
            48=>'dm',
            49=>'do',
            50=>'tl',
            51=>'ec',
            52=>'eg',
            53=>'sv',
            54=>'gq',
            55=>'er',
            56=>'ee',
            57=>'et',
            58=>'fj',
            59=>'fi',
            60=>'fr',
            61=>'ga',
            62=>'gm',
            63=>'ge',
            65=>'gh',
            66=>'gr',
            67=>'gd',
            68=>'gt',
            69=>'gn',
            70=>'gw',
            71=>'gy',
            72=>'ht',
            73=>'hn',
            74=>'hu',
            75=>'is',
            76=>'in',
            77=>'id',
            78=>'ir',
            79=>'iq',
            80=>'ie',
            81=>'il',
            82=>'it',
            83=>'ci',
            84=>'jm',
            85=>'jp',
            86=>'jo',
            87=>'kz',
            88=>'ke',
            89=>'ki',
            90=>'kp',
            91=>'kr',
            92=>'kosovo',
            93=>'kw',
            94=>'kg',
            95=>'la',
            96=>'lv',
            97=>'lb',
            98=>'ls',
            99=>'lr',
            100=>'ly',
            101=>'li',
            102=>'lt',
            103=>'lu',
            104=>'mk',
            105=>'mg',
            106=>'mw',
            107=>'my',
            108=>'mv',
            109=>'ml',
            110=>'mt',
            111=>'mh',
            112=>'mr',
            113=>'mu',
            114=>'mx',
            115=>'fm',
            116=>'md',
            117=>'mc',
            118=>'mn',
            119=>'me',
            120=>'ma',
            121=>'mz',
            122=>'mm',
            123=>'na',
            124=>'nr',
            125=>'np',
            126=>'nl',
            127=>'nz',
            128=>'ni',
            129=>'ne',
            130=>'ng',
            131=>'no',
            132=>'om',
            133=>'pk',
            134=>'pw',
            135=>'pa',
            136=>'pg',
            137=>'py',
            138=>'pe',
            139=>'ph',
            140=>'pl',
            141=>'pt',
            142=>'qa',
            143=>'ro',
            144=>'ru',
            145=>'rw',
            146=>'kn',
            147=>'lc',
            148=>'vc',
            149=>'ws',
            150=>'sm',
            151=>'st',
            152=>'sa',
            153=>'sn',
            154=>'rs',
            155=>'sc',
            156=>'sl',
            157=>'sg',
            158=>'sk',
            159=>'si',
            160=>'sb',
            161=>'so',
            162=>'za',
            163=>'ss',
            164=>'es',
            165=>'lk',
            166=>'sd',
            167=>'sr',
            168=>'sz',
            169=>'se',
            171=>'sy',
            172=>'tw',
            173=>'tj',
            174=>'tz',
            175=>'th',
            176=>'tg',
            177=>'to',
            178=>'tt',
            179=>'tn',
            180=>'tr',
            181=>'tm',
            182=>'tv',
            183=>'ug',
            184=>'ua',
            185=>'ae',
            186=>'gb',
            187=>'us',
            188=>'uy',
            189=>'uz',
            190=>'vu',
            191=>'va',
            192=>'ve',
            193=>'vn',
            194=>'ye',
            195=>'zm',
            196=>'zw'
        ];

        if($id==null){
		 return $countries;	
		}
		else{
		 return $countries[$id];
		}
    }
	
	public static function getCountryLanguage($id=null) {

        $countries = [
            64=> 'de',
            10=> 'de',
            170=> 'de',
            1=> 'en',
            2=> 'en',
            3=> 'en',
            4=> 'en',
            5=> 'en',
            6=> 'en',
            7=> 'en',
            8=> 'en',
            9=> 'en',
            11=> 'en',
            12=> 'en',
            13=> 'en',
            14=> 'en',
            15=> 'en',
            16=> 'ru',
            17=> 'en',
            18=> 'en',
            19=> 'en',
            20=> 'en',
            21=> 'en',
            22=> 'en',
            23=> 'en',
            24=> 'en',
            25=> 'en',
            26=> 'en',
            27=> 'en',
            28=> 'en',
            29=> 'en',
            30=> 'en',
            31=> 'en',
            32=> 'en',
            33=> 'en',
            34=> 'en',
            35=> 'en',
            36=> 'en',
            37=> 'en',
            38=> 'en',
            39=> 'en',
            40=> 'en',
            41=> 'en',
            42=> 'en',
            43=> 'en',
            44=> 'en',
            45=> 'en',
            46=> 'en',
            47=> 'en',
            48=> 'en',
            49=> 'en',
            50=> 'en',
            51=> 'en',
            52=> 'en',
            53=> 'en',
            54=> 'en',
            55=> 'en',
            56=> 'en',
            57=> 'en',
            58=> 'en',
            59=> 'en',
            60=> 'en',
            61=> 'en',
            62=> 'en',
            63=> 'en',
            65=> 'en',
            66=> 'en',
            67=> 'en',
            68=> 'en',
            69=> 'en',
            70=> 'en',
            71=> 'en',
            72=> 'en',
            73=> 'en',
            74=> 'en',
            75=> 'en',
            76=> 'en',
            77=> 'en',
            78=> 'en',
            79=> 'en',
            80=> 'en',
            81=> 'en',
            82=> 'en',
            83=> 'en',
            84=> 'en',
            85=> 'en',
            86=> 'en',
            87=> 'ru',
            88=> 'en',
            89=> 'en',
            90=> 'en',
            91=> 'en',
            92=> 'en',
            93=> 'en',
            94=> 'en',
            95=> 'en',
            96=> 'en',
            97=> 'en',
            98=> 'en',
            99=> 'en',
            100=> 'en',
            101=> 'de',
            102=> 'en',
            103=> 'en',
            104=> 'en',
            105=> 'en',
            106=> 'en',
            107=> 'en',
            108=> 'en',
            109=> 'en',
            110=> 'en',
            111=> 'en',
            112=> 'en',
            113=> 'en',
            114=> 'en',
            115=> 'en',
            116=> 'en',
            117=> 'en',
            118=> 'en',
            119=> 'en',
            120=> 'en',
            121=> 'en',
            122=> 'en',
            123=> 'en',
            124=> 'en',
            125=> 'en',
            126=> 'en',
            127=> 'en',
            128=> 'en',
            129=> 'en',
            130=> 'en',
            131=> 'en',
            132=> 'en',
            133=> 'en',
            134=> 'en',
            135=> 'en',
            136=> 'en',
            137=> 'en',
            138=> 'en',
            139=> 'en',
            140=> 'en',
            141=> 'en',
            142=> 'en',
            143=> 'en',
            144=> 'ru',
            145=> 'en',
            146=> 'en',
            147=> 'en',
            148=> 'en',
            149=> 'en',
            150=> 'en',
            151=> 'en',
            152=> 'en',
            153=> 'en',
            154=> 'en',
            155=> 'en',
            156=> 'en',
            157=> 'en',
            158=> 'en',
            159=> 'en',
            160=> 'en',
            161=> 'en',
            162=> 'en',
            163=> 'en',
            164=> 'en',
            165=> 'en',
            166=> 'en',
            167=> 'en',
            168=> 'en',
            169=> 'en',
            171=> 'en',
            172=> 'en',
            173=> 'en',
            174=> 'en',
            175=> 'en',
            176=> 'en',
            177=> 'en',
            178=> 'en',
            179=> 'en',
            180=> 'en',
            181=> 'en',
            182=> 'en',
            183=> 'en',
            184=> 'en',
            185=> 'en',
            186=> 'en',
            187=> 'en',
            188=> 'en',
            189=> 'en',
            190=> 'en',
            191=> 'en',
            192=> 'en',
            193=> 'en',
            194=> 'en',
            195=> 'en',
            196=> 'en'
        ];
		if($id==null){
		 return $countries[196];	
		}
		else{
		 return $countries[$id];	
		}
       
    }
	public static function getCountryIdByCode($code) {

        $countries = [
          'de' => 64,
          'at' => 10,
          'ch' => 170,
		   'af'=>1,
		   'al'=>2,
		   'dz'=>3,
		   'ad'=>4,
		   'ao'=>5,
		   'ag'=>6,
		   'ar'=>7,
		   'am'=>8,
		   'au'=>9,
            'az'=>11,
            'bs'=>12,
            'bh'=>13,
            'bd'=>14,
            'bb'=>15,
            'by'=>16,
            'be'=>17,
            'bz'=>18,
            'bj'=>19,
            'bm'=>20,
            'bo'=>21,
            'ba'=>22,
            'bw'=>23,
            'br'=>24,
            'bn'=>25,
            'bg'=>26,
            'bf'=>27,
            'bi'=>28,
            'kh'=>29,
            'cm'=>30,
            'ca'=>31,
            'cv'=>32,
            'cf'=>33,
            'td'=>34,
            'cl'=>35,
            'cn'=>36,
            'co'=>37,
            'km'=>38,
            'cg'=>39,
            'cd'=>40,
            'cr'=>41,
            'hr'=>42,
            'cu'=>43,
            'cy'=>44,
            'cz'=>45,
            'dk'=>46,
            'dj'=>47,
            'dm'=>48,
            'do'=>49,
            'tl'=>50,
            'ec'=>51,
            'eg'=>52,
            'sv'=>53,
            'gq'=>54,
            'er'=>55,
            'ee'=>56,
            'et'=>57,
            'fj'=>58,
            'fi'=>59,
            'fr'=>60,
            'ga'=>61,
            'gm'=>62,
            'ge'=>63,
            'gh'=>65,
            'gr'=>66,
            'gd'=>67,
            'gt'=>68,
            'gn'=>69,
            'gw'=>70,
            'gy'=>71,
            'ht'=>72,
            'hn'=>73,
            'hu'=>74,
            'is'=>75,
            'in'=>76,
            'id'=>77,
            'ir'=>78,
            'iq'=>79,
            'ie'=>80,
            'il'=>81,
            'it'=>82,
            'ci'=>83,
            'jm'=>84,
            'jp'=>85,
            'jo'=>86,
            'kz'=>87,
            'ke'=>88,
            'ki'=>89,
            'kp'=>90,
            'kr'=>91,
            'ko'=>92,
            'kw'=>93,
            'kg'=>94,
            'la'=>95,
            'lv'=>96,
            'lb'=>97,
            'ls'=>98,
            'lr'=>99,
            'ly'=>100,
            'li'=>101,
            'lt'=>102,
            'lu'=>103,
            'mk'=>104,
            'mg'=>105,
            'mw'=>106,
            'my'=>107,
            'mv'=>108,
            'ml'=>109,
            'mt'=>110,
            'mh'=>111,
            'mr'=>112,
            'mu'=>113,
            'mx'=>114,
            'fm'=>115,
            'md'=>116,
            'mc'=>117,
            'mn'=>118,
            'me'=>119,
            'ma'=>120,
            'mz'=>121,
            'mm'=>122,
            'na'=>123,
            'nr'=>124,
            'np'=>125,
            'nl'=>126,
            'nz'=>127,
            'ni'=>128,
            'ne'=>129,
            'ng'=>130,
            'no'=>131,
            'om'=>132,
            'pk'=>133,
            'pw'=>134,
            'pa'=>135,
            'pg'=>136,
            'py'=>137,
            'pe'=>138,
            'ph'=>139,
            'pl'=>140,
            'pt'=>141,
            'qa'=>142,
            'ro'=>143,
            'ru'=>144,
            'rw'=>145,
            'kn'=>146,
            'lc'=>147,
            'vc'=>148,
            'ws'=>149,
            'sm'=>150,
            'st'=>151,
            'sa'=>152,
            'sn'=>153,
            'rs'=>154,
            'sc'=>155,
            'sl'=>156,
            'sg'=>157,
            'sk'=>158,
            'si'=>159,
            'sb'=>160,
            'so'=>161,
            'za'=>162,
            'ss'=>163,
            'es'=>164,
            'lk'=>165,
            'sd'=>166,
            'sr'=>167,
            'sz'=>168,
            'se'=>169,
            'sy'=>171,
            'tw'=>172,
            'tj'=>173,
            'tz'=>174,
            'th'=>175,
            'tg'=>176,
            'to'=>177,
            'tt'=>178,
            'tn'=>179,
            'tr'=>180,
            'tm'=>181,
            'tv'=>182,
            'ug'=>183,
            'ua'=>184,
            'ae'=>185,
            'gb'=>186,
            'us'=>187,
            'uy'=>188,
            'uz'=>189,
            'vu'=>190,
            'va'=>191,
            've'=>192,
            'vn'=>193,
            'ye'=>194,
            'zm'=>195,
            'zw'=>196
        ];

       
		 return $countries[$code];	
		
		
    }

    public static function getLocation() {
        $reader = new \GeoIp2\Database\Reader(Yii::getAlias('@app').'/data/GeoLite2-Country.mmdb');
        $location = [];
        try {
            $ip = Yii::$app->request->userIP;
            $record = $reader->country($ip);
            $location = [
                'name'=> $record->country->name,
                'code'=> $record->country->isoCode,
            ];

        } catch (\GeoIp2\Exception\AddressNotFoundException $e) {

        }

        return $location;
    }

	public static function getId() {
        $location = static::getLocation();
        $id = static::getCountryIdByCode(strtolower($location['code']));
        if (!$location || !$id) return 64;
        return $id;
    }

    public static function getCode() {
        $location = static::getLocation();
        if (!$location) return 'de';
        return strtolower($location['code']);
    }


}
